services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: mortydb
      MYSQL_USER: morty
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_0900_ai_ci", "--default-time-zone=+00:00" ]
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
